### ISSUE TITLE
About 100k of answers of sam data is `"what is the difference between a man and a woman?"' 

### ISSUE THREAD

**Issue by janghyuncho** [OpenGVLab/all-seeing#18]
I guess there was some kind of a bug? See, for example:
![image](https://github.com/OpenGVLab/all-seeing/assets/77150595/f1240623-97b9-4919-9cd1-5eb59c3f4b58)

{'id': -1,
 'image': 'sam/sa_000044/sa_500317.jpg',
 'height': 1500,
 'width': 2666,
 'conversations': [{'from': 'human',
   'value': '<image>\nWhat is the primary function of these missiles? Please answer the question according to this region: <box>[[529, 530, 590, 622]]</box>.'},
  {'from': 'gpt',
   'value': '"What is the difference between a man and a woman?"'},
  {'from': 'human',
   'value': 'What is the primary function of these missiles? Please answer the question according to this region: <box>[[606, 597, 750, 737]]</box>.'},
  {'from': 'gpt',
   'value': '"What is the difference between a man and a woman?"'}]}

**Comment by muyuelingxiao** [comment]
Excuse me, could you find the file "asmv2-13b.jsonl"? I cant find the location to download it when evaluating.

**Comment by Weiyun1025** [comment]
Sorry for the late response.

You should input `<image>\nWhat is the primary function of these missiles? Please answer the question according to this region` instead of `\nWhat is the primary function of these missiles? Please answer the question according to this region` to ensure the image is properly inputted into the model..

**Comment by janghyuncho** [comment]
This is your annotation.
